name: Deploy to Hetzner Server

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: wasm32-unknown-unknown
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: package-lock.json
        
    - name: Install cargo-leptos
      run: cargo install cargo-leptos
      
    - name: Install npm dependencies
      run: npm ci

    - name: Build Leptos application
      run: cargo leptos build --release

    - name: Create deployment archive
      run: |
        mkdir -p deploy
        cp -r target/site/* deploy/
        cp target/release/leptos-radix-ui deploy/
        tar -czf leptos-radix-ui-deploy.tar.gz -C deploy .
        
    - name: Deploy to new server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.NEW_SERVER_HOST }}
        username: ${{ secrets.NEW_SERVER_USER }}
        key: ${{ secrets.NEW_SERVER_SSH_KEY }}
        port: 22
        script: |
          # Create deployment directory
          sudo mkdir -p /var/www/leptographic
          sudo chown $USER:$USER /var/www/leptographic
          
          # Stop existing service if running
          sudo systemctl stop leptographic || true

          # Backup current deployment
          if [ -d "/var/www/leptographic/current" ]; then
            sudo mv /var/www/leptographic/current /var/www/leptographic/backup-$(date +%Y%m%d-%H%M%S)
          fi

          # Create new deployment directory
          mkdir -p /var/www/leptographic/current
          
    - name: Upload deployment files
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.NEW_SERVER_HOST }}
        username: ${{ secrets.NEW_SERVER_USER }}
        key: ${{ secrets.NEW_SERVER_SSH_KEY }}
        port: 22
        source: "leptos-radix-ui-deploy.tar.gz"
        target: "/tmp/"
        
    - name: Extract and start application
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.NEW_SERVER_HOST }}
        username: ${{ secrets.NEW_SERVER_USER }}
        key: ${{ secrets.NEW_SERVER_SSH_KEY }}
        port: 22
        script: |
          # Extract deployment files
          cd /var/www/leptographic/current
          tar -xzf /tmp/leptos-radix-ui-deploy.tar.gz
          chmod +x leptos-radix-ui

          # Clean up temp file
          rm /tmp/leptos-radix-ui-deploy.tar.gz

          # Start the service
          sudo systemctl start leptographic
          sudo systemctl enable leptographic

          # Check service status
          sudo systemctl status leptographic
