name: Test Build

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  test-build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@4305c38b25d97ef35a8ad1f985ccf2d2242004f2 # stable
      with:
        targets: wasm32-unknown-unknown

    - name: Cache Rust dependencies
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-
        
    - name: Setup Node.js
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: package-lock.json
        
    - name: Install cargo-leptos (cached)
      run: |
        if ! command -v cargo-leptos &> /dev/null; then
          cargo install cargo-leptos --version 0.2.40
        else
          echo "cargo-leptos already installed"
        fi

    - name: Install npm dependencies
      run: npm ci

    - name: Run Rust tests
      run: cargo test --lib --bins

    - name: Check Rust formatting
      run: cargo fmt --check

    - name: Run Clippy
      run: cargo clippy -- -D warnings

    - name: Build Leptos application (debug)
      run: cargo leptos build
        
    - name: Verify build artifacts
      run: |
        echo "Checking build artifacts..."
        ls -la target/site/
        ls -la target/debug/
        echo "Build test completed successfully!"
